services:
  db:
    image: postgres:13
    container_name: pixelbattle_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixelbattle
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5435:5432
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
    db: